services:
  - type: web
    name: learnsync-lms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: DATABASE_URL
        sync: false